In [173]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

# Load MovieLens dataset (assuming you have 'ratings.csv', 'movies.csv', and 'tags.csv')
ratings = pd.read_csv('ratings.csv')
movies = pd.read_csv('movies.csv')
tags = pd.read_csv('tags.csv')

In [174]:
ratings.head(3)

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224

In [175]:
movies.head(3)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance

In [176]:
tags.head(3)

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992

In [177]:

user_item_matrix = ratings.pivot(index='userId', columns='movieId', values='rating').fillna(0)
user_item_matrix #User-item interaction matrix

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,2.5,0.0,0.0,0.0,0.0,0.0,2.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,2.5,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
609,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,5.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [178]:
user_similarity = cosine_similarity(user_item_matrix)
user_similarity_df = pd.DataFrame(user_similarity, index=user_item_matrix.index, columns=user_item_matrix.index)
user_similarity_df #Cosine similarity matrix (two userID array dot product divided by their magnitudes )

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.027283,0.059720,0.194395,0.129080,0.128152,0.158744,0.136968,0.064263,0.016875,...,0.080554,0.164455,0.221486,0.070669,0.153625,0.164191,0.269389,0.291097,0.093572,0.145321
2,0.027283,1.000000,0.000000,0.003726,0.016614,0.025333,0.027585,0.027257,0.000000,0.067445,...,0.202671,0.016866,0.011997,0.000000,0.000000,0.028429,0.012948,0.046211,0.027565,0.102427
3,0.059720,0.000000,1.000000,0.002251,0.005020,0.003936,0.000000,0.004941,0.000000,0.000000,...,0.005048,0.004892,0.024992,0.000000,0.010694,0.012993,0.019247,0.021128,0.000000,0.032119
4,0.194395,0.003726,0.002251,1.000000,0.128659,0.088491,0.115120,0.062969,0.011361,0.031163,...,0.085938,0.128273,0.307973,0.052985,0.084584,0.200395,0.131746,0.149858,0.032198,0.107683
5,0.129080,0.016614,0.005020,0.128659,1.000000,0.300349,0.108342,0.429075,0.000000,0.030611,...,0.068048,0.418747,0.110148,0.258773,0.148758,0.106435,0.152866,0.135535,0.261232,0.060792
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.164191,0.028429,0.012993,0.200395,0.106435,0.102123,0.200035,0.099388,0.075898,0.088963,...,0.178084,0.116534,0.300669,0.066032,0.148141,1.000000,0.153063,0.262558,0.069622,0.201104
607,0.269389,0.012948,0.019247,0.131746,0.152866,0.162182,0.186114,0.185142,0.011844,0.010451,...,0.092525,0.199910,0.203540,0.137834,0.118780,0.153063,1.000000,0.283081,0.149190,0.139114
608,0.291097,0.046211,0.021128,0.149858,0.135535,0.178809,0.323541,0.187233,0.100435,0.077424,...,0.158355,0.197514,0.232771,0.155306,0.178142,0.262558,0.283081,1.000000,0.121993,0.322055
609,0.093572,0.027565,0.000000,0.032198,0.261232,0.214234,0.090840,0.423993,0.000000,0.021766,...,0.035653,0.335231,0.061941,0.236601,0.097610,0.069622,0.149190,0.121993,1.000000,0.053225
610,0.145321,0.102427,0.032119,0.107683,0.060792,0.052668,0.193219,0.078153,0.074399,0.121072,...,0.222491,0.087528,0.163094,0.052552,0.119295,0.201104,0.139114,0.322055,0.053225,1.000000

In [179]:
#Group all tags in a movie together
movie_tags = tags.groupby('movieId')['tag'].apply(' '.join).reset_index()

#Merge movie data with tags
movie_data = pd.merge(movies, movie_tags, on='movieId', how='left')
movie_data['tag'] = movie_data['tag'].fillna('')

movie_data

,movieId,title,genres,tag
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,pixar pixar fun
1,2,Jumanji (1995),Adventure|Children|Fantasy,fantasy magic board game Robin Williams game
2,3,Grumpier Old Men (1995),Comedy|Romance,moldy old
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,
4,5,Father of the Bride Part II (1995),Comedy,pregnancy remake
...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,
9739,193585,Flint (2017),Drama,
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,

In [180]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf_vectorizer.fit_transform(movie_data['genres'] + ' ' + movie_data['tag'])
tfidf_vectorizer.vocabulary_

{'adventure': 36,
 'animation': 75,
 'children': 274,
 'comedy': 317,
 'fantasy': 530,
 'pixar': 1142,
 'fun': 587,
 'magic': 925,
 'board': 177,
 'game': 595,
 'robin': 1263,
 'williams': 1651,
 'romance': 1271,
 'moldy': 992,
 'old': 1081,
 'drama': 453,
 'pregnancy': 1172,
 'remake': 1235,
 'action': 22,
 'crime': 363,
 'thriller': 1516,
 'politics': 1156,
 'president': 1175,
 'horror': 725,
 'mafia': 923,
 'jane': 811,
 'austen': 110,
 'hollywood': 713,
 'mystery': 1025,
 'serial': 1334,
 'killer': 853,
 'sci': 1311,
 'fi': 547,
 'alcoholism': 49,
 'shakespeare': 1344,
 'netflix': 1048,
 'queue': 1201,
 'kidnapping': 851,
 'high': 696,
 'school': 1309,
 'teacher': 1487,
 'time': 1524,
 'travel': 1547,
 'brad': 194,
 'pitt': 1141,
 'bruce': 211,
 'willis': 1652,
 'mindfuck': 980,
 'post': 1163,
 'apocalyptic': 84,
 'twist': 1564,
 'ending': 491,
 'animal': 73,
 'movie': 1012,
 'pigs': 1139,
 'villain': 1604,
 'nonexistent': 1063,
 'needed': 1040,
 'good': 627,
 'story': 1431,
 'death': 399,
 'penalty': 1123,
 'nun': 1073,
 'twins': 1563,
 'chick': 271,
 'flick': 563,
 'funny': 588,
 'paul': 1118,
 'rudd': 1278,
 'quotable': 1205,
 'seen': 1328,
 'emma': 487,
 'south': 1393,
 'africa': 39,
 'war': 1620,
 'england': 493,
 'journalism': 835,
 'wedding': 1631,
 'musical': 1024,
 'suspense': 1468,
 'tricky': 1552,
 'heist': 686,
 'adoption': 30,
 'prostitution': 1184,
 'writing': 1666,
 'music': 1023,
 'documentary': 438,
 'jekyll': 819,
 'hyde': 746,
 'theater': 1507,
 'beat': 139,
 'quirky': 1204,
 'test': 1504,
 'tag': 1481,
 'golf': 625,
 'adam': 25,
 'sandler': 1294,
 'muppets': 1019,
 'beautiful': 141,
 'scenery': 1305,
 'epic': 502,
 'historical': 704,
 'inspirational': 781,
 'medieval': 956,
 'mel': 958,
 'gibson': 618,
 'oscar': 1094,
 'best': 152,
 'cinematography': 290,
 'revenge': 1244,
 'sword': 1477,
 'fight': 550,
 'scotland': 1317,
 'assassination': 101,
 'holocaust': 714,
 'dating': 390,
 'addiction': 28,
 'heroin': 694,
 'leonardo': 881,
 'dicaprio': 415,
 'mark': 935,
 'wahlberg': 1615,
 'imax': 757,
 'moon': 998,
 'nasa': 1034,
 'space': 1395,
 'superhero': 1459,
 'michael': 972,
 'crichton': 362,
 'submarine': 1449,
 'western': 1638,
 'film': 555,
 'noir': 1059,
 'controversial': 335,
 'new': 1049,
 'york': 1669,
 'city': 292,
 'nudity': 1072,
 'frontal': 583,
 'computers': 324,
 'generation': 607,
 'stop': 1429,
 'looking': 903,
 'swan': 1472,
 'ireland': 796,
 'cynical': 380,
 'hilarious': 699,
 'independent': 765,
 'witty': 1658,
 'mental': 965,
 'illness': 751,
 'psychology': 1190,
 'stephen': 1420,
 'king': 855,
 'business': 224,
 'basketball': 134,
 'france': 572,
 'infertility': 773,
 'australia': 112,
 'bad': 126,
 'sinbad': 1362,
 'beethoven': 146,
 'einstein': 481,
 'court': 350,
 'classic': 298,
 'great': 639,
 'soundtrack': 1392,
 'engrossing': 494,
 'nerd': 1046,
 'oldie': 1082,
 'goodie': 628,
 'star': 1415,
 'wars': 1622,
 'robots': 1264,
 'androids': 68,
 'darth': 389,
 'vader': 1589,
 'luke': 915,
 'skywalker': 1370,
 'opera': 1086,
 'louisa': 909,
 'alcott': 50,
 'girl': 620,
 'power': 1167,
 'india': 766,
 'gothic': 633,
 'christmas': 283,
 'prison': 1179,
 'disability': 426,
 'brutality': 213,
 'dark': 388,
 'psychedelic': 1187,
 'satire': 1296,
 'stylized': 1448,
 'assassin': 100,
 'jean': 817,
 'reno': 1239,
 'hit': 706,
 'men': 963,
 'assassins': 102,
 'awkward': 121,
 'corruption': 345,
 'disturbing': 432,
 'french': 580,
 'friendship': 582,
 'gary': 603,
 'oldman': 1083,
 'acting': 21,
 'guns': 653,
 'hitman': 708,
 'humorous': 742,
 'imdb': 758,
 '250': 9,
 'lolita': 898,
 'theme': 1508,
 'loneliness': 899,
 'love': 910,
 'luc': 912,
 'besson': 151,
 'natalie': 1035,
 'portman': 1162,
 'organized': 1090,
 'police': 1154,
 'sniper': 1379,
 'tense': 1500,
 'touching': 1536,
 'unique': 1577,
 'dialogue': 413,
 'non': 1062,
 'linear': 891,
 'cult': 374,
 'drugs': 460,
 'quentin': 1200,
 'tarantino': 1485,
 '1990s': 7,
 'achronological': 20,
 'packed': 1101,
 'aggressive': 42,
 'amazing': 57,
 'dialogues': 414,
 'anthology': 79,
 'atmospheric': 106,
 'awesome': 120,
 'ass': 99,
 'language': 869,
 'bible': 155,
 'biblical': 156,
 'references': 1229,
 'big': 157,
 'boys': 193,
 'actors': 23,
 'black': 166,
 'humor': 741,
 'humour': 743,
 'blood': 171,
 'splatters': 1407,
 'bloody': 173,
 'casual': 249,
 'violence': 1605,
 'character': 259,
 'development': 410,
 'characters': 261,
 'coke': 309,
 'conversation': 337,
 'cool': 338,
 'style': 1446,
 'scene': 1304,
 'scrubbing': 1322,
 'dance': 384,
 'dancing': 385,
 'different': 419,
 'diner': 420,
 'disjointed': 430,
 'timeline': 1525,
 'drug': 459,
 'overdose': 1097,
 'ensemble': 497,
 'cast': 248,
 'entertaining': 500,
 'entirely': 501,
 'episodic': 503,
 'exciting': 517,
 'fast': 533,
 'paced': 1099,
 'foul': 571,
 'gangster': 598,
 'gangsters': 599,
 'genius': 608,
 'golden': 624,
 'watch': 1624,
 'gore': 631,
 'gritty': 645,
 'harvey': 675,
 'keitel': 849,
 'highly': 697,
 'homosexuality': 717,
 'iconic': 748,
 'innovative': 776,
 'intellectual': 784,
 'intelligent': 786,
 'intense': 787,
 'interesting': 788,
 'intertwining': 790,
 'storylines': 1433,
 'interwoven': 791,
 'ironic': 797,
 'irony': 798,
 'john': 825,
 'travolta': 1548,
 'protagonist': 1185,
 'los': 906,
 'angeles': 70,
 'masterpiece': 943,
 'meaningless': 953,
 'milkshake': 977,
 'mobster': 988,
 'mobsters': 989,
 'monologue': 994,
 'motherfucker': 1006,
 'multiple': 1018,
 'stories': 1430,
 'neo': 1045,
 'nonlinear': 1064,
 'narrative': 1033,
 'storyline': 1432,
 'notable': 1070,
 'offensive': 1078,
 'organised': 1088,
 'original': 1091,
 'plot': 1148,
 'order': 1087,
 'palme': 1106,
 'parody': 1114,
 'philosophical': 1132,
 'pop': 1160,
 'culture': 375,
 'psychological': 1189,
 'pulp': 1194,
 'violent': 1606,
 'content': 334,
 'including': 764,
 'rape': 1216,
 'images': 753,
 'graphic': 638,
 'sexuality': 1341,
 'strong': 1441,
 'sustained': 1471,
 'random': 1213,
 'retro': 1242,
 'roger': 1266,
 'avary': 117,
 'royal': 1276,
 'cheese': 267,
 'samuel': 1292,
 'jackson': 807,
 'sarcasm': 1295,
 'sexy': 1342,
 'smart': 1377,
 'sophisticated': 1390,
 'splatter': 1406,
 'steve': 1421,
 'buscemi': 223,
 'storytelling': 1434,
 'stylish': 1447,
 'thought': 1514,
 'provoking': 1186,
 'uma': 1567,
 'thurman': 1519,
 'unpredictable': 1582,
 'unusual': 1584,
 'tv': 1562,
 'marriage': 937,
 'wrongful': 1667,
 'imprisonment': 762,
 'morgan': 1001,
 'freeman': 579,
 'enterprise': 498,
 'coma': 316,
 'weddings': 1632,
 'cross': 367,
 'dressing': 457,
 'drag': 452,
 'remade': 1234,
 'tom': 1533,
 'clancy': 295,
 'grisham': 644,
 'interracial': 789,
 'shrimp': 1355,
 'vietnam': 1601,
 'bubba': 214,
 'gump': 650,
 'lieutenant': 888,
 'dan': 383,
 'stupid': 1445,
 'does': 440,
 'bittersweet': 163,
 'emotional': 488,
 'heartwarming': 684,
 'gambling': 594,
 'disney': 431,
 'animated': 74,
 'feature': 539,
 'score': 1315,
 'bus': 222,
 'spies': 1405,
 'christina': 282,
 'ricci': 1248,
 'christopher': 285,
 'lloyd': 897,
 'family': 529,
 'edith': 476,
 'wharton': 1640,
 'horses': 726,
 'actress': 24,
 'al': 45,
 'pacino': 1100,
 'based': 133,
 'hula': 738,
 'hoop': 718,
 'biopic': 161,
 'dinosaur': 422,
 'japan': 812,
 'divorce': 434,
 'aids': 44,
 'radio': 1211,
 'butler': 226,
 'housekeeper': 732,
 'military': 976,
 'racism': 1209,
 'football': 566,
 'moving': 1014,
 'true': 1556,
 'biography': 160,
 'chess': 270,
 'lewis': 885,
 'large': 870,
 'race': 1207,
 'empire': 489,
 'state': 1417,
 'building': 218,
 'artificial': 93,
 'intelligence': 785,
 'cyberpunk': 378,
 'future': 589,
 'philip': 1131,
 'dick': 417,
 'dreamlike': 454,
 'existentialism': 519,
 'poetry': 1151,
 'halloween': 658,
 'knights': 860,
 'adolescence': 29,
 'overrated': 1098,
 'apocalypse': 83,
 'arnold': 89,
 'schwarzenegger': 1310,
 'nuclear': 1071,
 'scifi': 1314,
 'american': 59,
 'indians': 768,
 'native': 1037,
 'americans': 60,
 'hannibal': 664,
 'lector': 878,
 'coen': 308,
 'brothers': 210,
 'edward': 477,
 'norton': 1068,
 'priest': 1177,
 'babies': 123,
 'gulf': 649,
 'spoof': 1408,
 'bugs': 217,
 'bunny': 220,
 'veterinarian': 1598,
 'aardman': 13,
 'alcatraz': 48,
 'bay': 137,
 'terrorism': 1503,
 'disaster': 428,
 'aliens': 53,
 'atomic': 107,
 'bomb': 181,
 'purity': 1195,
 'essence': 506,
 'slim': 1374,
 'pickens': 1137,
 'book': 184,
 'narrated': 1032,
 'abuse': 17,
 'adultery': 35,
 'son': 1389,
 'melodramatic': 961,
 'kind': 854,
 'dumb': 463,
 'cinema': 289,
 'capote': 238,
 'falling': 527,
 'alfred': 51,
 'hitchcock': 707,
 'james': 810,
 'stewart': 1423,
 'voyeurism': 1613,
 'photographer': 1135,
 'photography': 1136,
 'screwball': 1320,
 'brooch': 208,
 'mount': 1010,
 'rushmore': 1281,
 'start': 1416,
 'statue': 1419,
 'george': 612,
 'bernard': 149,
 'shaw': 1347,
 'rich': 1249,
 'guy': 654,
 'poor': 1158,
 'italy': 803,
 'royalty': 1277,
 '1900s': 1,
 'dorothy': 445,
 'toto': 1535,
 'civil': 293,
 'television': 1498,
 'movies': 1013,
 'eerie': 478,
 'rosebud': 1275,
 'hal': 656,
 'apes': 82,
 'arthur': 92,
 'clarke': 296,
 'computer': 323,
 'confusing': 327,
 'dull': 461,
 'futuristic': 590,
 'meditative': 957,
 'effects': 479,
 'visual': 1609,
 'relaxing': 1232,
 'revolutionary': 1246,
 'setting': 1337,
 'ship': 1350,
 'slow': 1375,
 'spacecraft': 1396,
 'stanley': 1413,
 'kubrick': 861,
 'superb': 1457,
 'surreal': 1465,
 'technology': 1492,
 'tedious': 1493,
 'visually': 1610,
 'appealing': 85,
 'mrs': 1017,
 'dewinter': 411,
 'europe': 510,
 'amnesia': 62,
 'cold': 310,
 'russia': 1283,
 'swashbuckler': 1474,
 'ghosts': 615,
 'shangri': 1345,
 'la': 865,
 'astaire': 103,
 'rogers': 1267,
 'homeless': 716,
 'oil': 1080,
 'nick': 1051,
 'nora': 1066,
 'charles': 262,
 'leopard': 882,
 'fugitive': 586,
 'zombies': 1675,
 'missionary': 985,
 'tennessee': 1499,
 'hemingway': 688,
 'food': 565,
 'nanny': 1030,
 'hammerstein': 661,
 'updated': 1585,
 'classics': 299,
 'anti': 81,
 'semitism': 1331,
 'governess': 634,
 'fish': 562,
 'religion': 1233,
 '1920s': 2,
 '1960s': 4,
 'jim': 824,
 'morrison': 1002,
 'predictable': 1170,
 'navy': 1038,
 '1950s': 3,
 'freedom': 578,
 'expression': 520,
 'aging': 43,
 'clousseau': 307,
 'british': 199,
 'monty': 996,
 'python': 1197,
 'boxing': 192,
 'jack': 804,
 'nicholson': 1050,
 'father': 535,
 'lucas': 913,
 'harrison': 672,
 'ford': 568,
 'sequel': 1333,
 'inigo': 775,
 'montoya': 995,
 'fingered': 560,
 'man': 930,
 'archaeology': 87,
 'indiana': 767,
 'jones': 832,
 'steven': 1422,
 'spielberg': 1404,
 'treasure': 1549,
 'hunt': 745,
 'ark': 88,
 'covenant': 352,
 'craft': 353,
 'spaghetti': 1398,
 'claustrophobic': 300,
 'confrontational': 326,
 'earnest': 469,
 'screenplay': 1319,
 'motivational': 1008,
 'middle': 974,
 'east': 471,
 'brainwashing': 196,
 'harper': 669,
 'lee': 879,
 'ferris': 544,
 'wheel': 1642,
 'venice': 1594,
 'zither': 1672,
 'samurai': 1293,
 'suspenseful': 1469,
 'norman': 1067,
 'bates': 135,
 'white': 1644,
 'saturday': 1298,
 'night': 1053,
 'live': 896,
 'mozart': 1016,
 'salieri': 1289,
 'entertainer': 499,
 'december': 401,
 'cerebral': 255,
 'reflective': 1230,
 'special': 1399,
 'sort': 1391,
 'highschool': 698,
 'simon': 1360,
 'garfunkel': 602,
 'pow': 1166,
 'incest': 763,
 'skiing': 1369,
 'chilly': 276,
 'creepy': 361,
 'menacing': 964,
 'oninous': 1085,
 'murder': 1020,
 'world': 1665,
 'ii': 750,
 'anime': 76,
 'stunning': 1444,
 'nazis': 1039,
 'gunfight': 652,
 'hammett': 662,
 'heavy': 685,
 'metal': 968,
 'mockumentary': 990,
 'holy': 715,
 'grail': 637,
 'forster': 570,
 'cambodia': 230,
 'baseball': 132,
 'birds': 162,
 'juliette': 840,
 'martin': 939,
 'scorsese': 1316,
 'robert': 1262,
 'niro': 1057,
 'lawyer': 875,
 'prom': 1182,
 'vampires': 1591,
 'demons': 403,
 'personals': 1128,
 'ads': 33,
 'borg': 186,
 'ex': 516,
 'miller': 978,
 'dogs': 441,
 'klingons': 859,
 'captain': 239,
 'kirk': 857,
 'whales': 1639,
 'shark': 1346,
 'sports': 1409,
 'spying': 1410,
 'slasher': 1371,
 'hawkeye': 678,
 'fennimore': 542,
 'cooper': 339,
 'conan': 325,
 'andrew': 66,
 'weber': 1630,
 'jungle': 841,
 'tolstoy': 1532,
 'reunion': 1243,
 'ballroom': 129,
 'dinosaurs': 423,
 'romantic': 1273,
 'transplants': 1545,
 '1970s': 5,
 'queen': 1199,
 'victoria': 1599,
 'lawyers': 876,
 'henry': 689,
 'amish': 61,
 'alternate': 56,
 'universe': 1578,
 'savannah': 1299,
 'canada': 235,
 'shipwreck': 1352,
 'kevin': 850,
 'costner': 346,
 'bowling': 191,
 'deadpan': 396,
 'jeff': 818,
 'bridges': 197,
 'goodman': 629,
 'julianne': 839,
 'moore': 999,
 'marijuana': 933,
 'seymour': 1343,
 'hoffman': 709,
 'ransom': 1214,
 'rug': 1280,
 'satirical': 1297,
 'dickens': 418,
 '1980s': 6,
 'dvd': 466,
 'conspiracy': 330,
 'avant': 116,
 'garde': 601,
 'elegiac': 484,
 'melancholy': 960,
 'wry': 1668,
 'hallucinatory': 659,
 'paranoid': 1109,
 'mathematics': 945,
 'artsy': 97,
 'enigmatic': 495,
 'insanity': 778,
 'paranoia': 1108,
 'ben': 147,
 'stiller': 1424,
 'crude': 370,
 'goofy': 630,
 'ships': 1351,
 'judaism': 837,
 'huey': 735,
 'long': 901,
 'penn': 1124,
 'warren': 1621,
 'coulda': 349,
 'contender': 333,
 'gangs': 597,
 'olympics': 1084,
 'china': 277,
 'autism': 113,
 'rasicm': 1217,
 'jason': 814,
 'california': 229,
 'mexico': 970,
 'katzanzakis': 845,
 'andy': 69,
 'garcia': 600,
 'francis': 574,
 'coppola': 341,
 'general': 606,
 'motors': 1009,
 'michigan': 973,
 'memory': 962,
 'suburbia': 1451,
 'carnival': 241,
 'ray': 1219,
 'bradbury': 195,
 'mermaid': 966,
 'weather': 1629,
 'forecaster': 569,
 'hinton': 701,
 'tolkein': 1530,
 'mice': 971,
 'college': 313,
 'scary': 1302,
 'aquarium': 86,
 'boston': 188,
 'capone': 237,
 'survival': 1467,
 'small': 1376,
 'towns': 1537,
 'train': 1542,
 'eyes': 522,
 'dobbler': 435,
 'freaks': 576,
 'snl': 1381,
 'broadway': 202,
 'poignant': 1152,
 'sentimental': 1332,
 'tear': 1490,
 'jerker': 821,
 'tearjerking': 1491,
 'america': 58,
 'cameo': 232,
 'whoopi': 1645,
 'goldberg': 623,
 'trek': 1550,
 'moses': 1005,
 'martial': 938,
 'arts': 96,
 'mail': 927,
 'doctors': 437,
 'hungary': 744,
 'stapler': 1414,
 'workplace': 1664,
 'nicolas': 1052,
 'cage': 228,
 'evil': 513,
 'siam': 1357,
 'philosophy': 1133,
 'nolan': 1060,
 'directorial': 425,
 'debut': 400,
 'southern': 1394,
 'golfing': 626,
 'virtual': 1608,
 'reality': 1222,
 'motherhood': 1007,
 'comic': 318,
 'prequel': 1174,
 'force': 567,
 'endings': 492,
 'spiders': 1403,
 'adult': 34,
 'free': 577,
 'speech': 1401,
 'park': 1112,
 'trey': 1551,
 'parker': 1113,
 'chris': 279,
 'klein': 858,
 'biggs': 158,
 'pizza': 1143,
 'beer': 145,
 'seann': 1324,
 'william': 1650,
 'scott': 1318,
 'teen': 1494,
 'claims': 294,
 'video': 1600,
 'crucifixion': 369,
 'rome': 1274,
 'slavery': 1372,
 'gentle': 611,
 'lyrical': 917,
 'nostalgia': 1069,
 'dead': 395,
 'people': 1125,
 'aviation': 118,
 'beatles': 140,
 'river': 1256,
 'academy': 18,
 'award': 119,
 'supporting': 1461,
 'indonesia': 771,
 'nightclub': 1054,
 'island': 800,
 'macaulay': 918,
 'culkin': 373,
 'challenging': 257,
 'chuck': 286,
 'palahniuk': 1104,
 'clever': 302,
 'complicated': 321,
 'consumerism': 331,
 'david': 391,
 'fincher': 559,
 'double': 446,
 'life': 889,
 'fighting': 551,
 'helena': 687,
 'bonham': 183,
 'carter': 243,
 'imaginary': 754,
 'friend': 581,
 'mind': 979,
 'blowing': 175,
 'topless': 1534,
 'palahnuik': 1105,
 'postmodern': 1164,
 'powerful': 1168,
 'schizophrenia': 1308,
 'social': 1383,
 'commentary': 320,
 'societal': 1384,
 'criticism': 366,
 'lawn': 873,
 'mower': 1015,
 'studio': 1442,
 'ghibli': 613,
 'tobacco': 1527,
 'marathon': 931,
 'class': 297,
 'aykroyd': 122,
 'camp': 234,
 'irreverent': 799,
 'jay': 815,
 'silent': 1358,
 'bob': 178,
 'smith': 1378,
 'series': 1335,
 'ichabod': 747,
 'crane': 355,
 'depression': 407,
 'dust': 465,
 'bowl': 190,
 'hanks': 663,
 'graham': 636,
 'greene': 641,
 'downbeat': 448,
 'fatherhood': 536,
 'kaufman': 846,
 'jude': 838,
 'law': 872,
 'obsession': 1075,
 'secrets': 1326,
 'asylum': 104,
 'brittany': 201,
 'murphy': 1021,
 'hospital': 727,
 'winona': 1656,
 'ryder': 1285,
 'dingo': 421,
 'ate': 105,
 'baby': 124,
 'nuns': 1074,
 'plastic': 1146,
 'surgery': 1463,
 'gun': 651,
 'fu': 584,
 'heroic': 693,
 'bloodshed': 172,
 'crazy': 357,
 'figure': 552,
 'skating': 1368,
 'circus': 291,
 'blind': 169,
 'orphans': 1093,
 'subway': 1452,
 'peace': 1119,
 'corp': 342,
 'scandal': 1301,
 'toga': 1528,
 'insurance': 783,
 'pearl': 1120,
 'buck': 215,
 'hepburn': 690,
 'tracy': 1538,
 'prejudice': 1173,
 'factory': 523,
 'pool': 1157,
 'evolution': 514,
 'hornby': 722,
 'peter': 1130,
 'pan': 1107,
 'families': 528,
 'jesse': 822,
 'ventura': 1595,
 'macho': 921,
 'psychiatrist': 1188,
 'rabbi': 1206,
 'sofia': 1386,
 'suicide': 1453,
 'ancient': 65,
 'history': 705,
 'russell': 1282,
 'crowe': 368,
 'romans': 1272,
 'pee': 1121,
 'wee': 1633,
 'herman': 691,
 'mining': 982,
 'easygoing': 472,
 'silly': 1359,
 'art': 90,
 'house': 731,
 'cryptic': 372,
 ...}

In [181]:
print(tfidf_matrix)

  (0, 587)	0.40432512831075756
  (0, 1142)	0.8416771249174413
  (0, 530)	0.17300098313924464
  (0, 317)	0.09576778805506665
  (0, 274)	0.18038846066758712
  (0, 75)	0.18490545901063682
  (0, 36)	0.14923127385752047
  (1, 1651)	0.3105613900424147
  (1, 1263)	0.33165713426090987
  (1, 595)	0.6850036759600161
  (1, 177)	0.35778658940156977
  (1, 925)	0.3055276791202499
  (1, 530)	0.2657634761752139
  (1, 274)	0.13855604603797952
  (1, 36)	0.11462426795143797
  (2, 1081)	0.6852356240039252
  (2, 992)	0.6852356240039252
  (2, 1271)	0.2026249156281861
  (2, 317)	0.14088088145157518
  (3, 453)	0.4666201177032598
  (3, 1271)	0.7261829999003466
  (3, 317)	0.5048999073185984
  (4, 1235)	0.6728033494323147
  (4, 1172)	0.7199029622585924
  (4, 317)	0.1705150372370789
  :	:
  (9732, 1236)	0.5511943752355779
  (9732, 619)	0.5511943752355779
  (9732, 76)	0.4424903666267339
  (9732, 547)	0.19139804035832575
  (9732, 1311)	0.19139804035832575
  (9732, 22)	0.15512521431325352
  (9732, 317)	0.22664539528929592
  (9732, 75)	0.21879993106093945
  (9733, 453)	0.4317490805956193
  (9733, 75)	0.9019937535287246
  (9734, 453)	0.678718734768546
  (9734, 317)	0.7343983109145773
  (9735, 75)	1.0
  (9736, 438)	1.0
  (9737, 22)	0.43582958319552006
  (9737, 530)	0.5751489486548335
  (9737, 317)	0.31838398612184327
  (9737, 75)	0.614725872770965
  (9738, 530)	0.6390336489541658
  (9738, 317)	0.35374850444543904
  (9738, 75)	0.6830065820377863
  (9739, 453)	1.0
  (9740, 22)	0.578369660285364
  (9740, 75)	0.815774807199507
  (9741, 317)	1.0

In [182]:
#Content based filtering
cosine_sim_content = cosine_similarity(tfidf_matrix, tfidf_matrix)
cosine_sim_content[0] #the problem lies in that some users have 0 similarity, this is the similarity with the first user with cosine similarity

array([1.        , 0.08807678, 0.01349185, ..., 0.        , 0.15084122,
       0.09576779])

In [183]:
#Collaborative filtering
#SVD factorization = used to simplify and represent the movie data
#Movie data is represented by a product of smaller matrices
#SVD factorization is known as A ≈ U x E x V^T, A is the input matrix
#Minimizing sum of squared errors of both LHS and RHS is SVD factorization
#Sum of Squared Errors is proportional to the square of standard deviation

R = user_item_matrix.values
U, sigma, Vt = np.linalg.svd(R, full_matrices=False)
sigma_matrix = np.diag(sigma)
predicted_ratings = np.dot(np.dot(U, sigma_matrix), Vt)

print('Standard Deviation of original matrix: ', np.std(R))
print('Standard Deviation of product: ', np.std(predicted_ratings))

Standard Deviation of original matrix:  0.4726144124098266
Standard Deviation of product:  0.4726144124098265

In [184]:
predicted_ratings[0] #the problem lies in that some users have 0 similarity, this is the similarity with the first user with SVD

array([ 4.00000000e+00,  3.67284328e-15,  4.00000000e+00, ...,
        1.71710519e-16,  1.92066415e-16, -6.87817858e-16])

In [188]:
def hybrid_recommendations(user_id, top_n=5):
    user_ratings = user_item_matrix.loc[user_id]
    collaborative_recs = pd.Series(predicted_ratings[user_id-1], index=user_item_matrix.columns).sort_values(ascending=False)
    #Collaborative recommendation ratings
    #Index of collaborative_recs is the movies that are most likely to be favored by a user
    
    content_recs = pd.Series((cosine_sim_content[user_item_matrix.columns.get_loc(item)] for item in collaborative_recs.index), index=collaborative_recs.index)
    content_recs = content_recs.sort_index()
    #Content-based Recommendation ratings
    #Find the cosine similarity of all items of a particular user, then sort index
        
    hybrid_recs = collaborative_recs + content_recs
    rating_index = user_ratings[user_ratings > 0].index
    hybrid_recs = hybrid_recs[~user_ratings.index.isin(rating_index)]  # Exclude items already rated
    return hybrid_recs

In [189]:
user_weights = [0.2, 0.8] #Can be adjusted as the size of the dataset or userbase grows
user_id = 3

In [190]:
recommended_movies = hybrid_recommendations(user_id)
print("Hybrid Recommended movies for user", user_id)
print(recommended_movies)

Hybrid Recommended movies for user 3
movieId
1    [0.9999999999999993, 0.08807678004317167, 0.01...
2    [0.08807678004312482, 0.9999999999999525, -4.7...
3    [0.013491850395764221, -1.0120376758848693e-13...
4    [0.0483531473131253, 1.4981722459839197e-14, 0...
5    [0.016329847946269484, -5.2886080931235924e-14...
dtype: object